services:
  leonardkabo-site:
    build: .
    container_name: leonardkabo-site
    restart: always
    env_file: .env 
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      # On utilise le même nom partout : leonardkabo-site
      - "traefik.http.routers.leonardkabo-site.rule=Host(`leonardkabo.cloud`) || Host(`www.leonardkabo.cloud`)"
      - "traefik.http.routers.leonardkabo-site.entrypoints=websecure"
      - "traefik.http.routers.leonardkabo-site.tls.certresolver=mytlschallenge"
      - "traefik.http.services.leonardkabo-site.loadbalancer.server.port=3000"

networks:
  traefik-network:
    external: true