version: '3.8'

services:
  leonardkabo-site:
    build: .
    container_name: leonardkabo-site
    restart: always
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leonardkabo.rule=Host(`leonardkabo.cloud`)"
      - "traefik.http.routers.leonardkabo.entrypoints=websecure"
      - "traefik.http.routers.leonardkabo.tls.certresolver=mytlschallenge"
      - "traefik.http.services.leonardkabo.loadbalancer.server.port=3000"

networks:
  traefik-public:
    external: true
